# Copyright 2024 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Open Match Installation
apiVersion: skaffold/v3
kind: Config
metadata:
  name: open-match-cfg
deploy:
  helm:
    releases:
      - name: open-match
        createNamespace: true
        namespace: "open-match"
        wait: true
        remoteChart: open-match
        repo: https://open-match.dev/chart/stable
        setValues:
          # Install the Default Evaluator
          open-match-customize.enabled: true
          open-match-customize.evaluator.enabled: true
          # Install ConfigMap `om-configmap-override`, this ConfigMap configures Open Match to talk to the Default Evaluator
          open-match-override.enabled: true
---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: guess-the-sketch-frontend-cfg
build:
  googleCloudBuild: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: guess-the-sketch-frontend
    context: .
manifests:
  rawYaml:
  - ./k8s.yaml
deploy:
  kubectl:
    defaultNamespace: genai
